### ISSUE TITLE
您说是原生，不依赖任何类库

### ISSUE THREAD

**Issue by lanweipeng** [liyupi/yu-image-uploader#1]
碰巧我使用的也是react，如果vue岂不是用不了。希望您在README.md能说明一下是react代码。

**Comment by liyupi** [comment]
好的非常感谢，现在就fix




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"兰为鹏"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 下午2:04
收件人:&nbsp;"liyupi/yu-image-uploader"<yu-image-uploader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[liyupi/yu-image-uploader] 您说是原生，不依赖任何类库 (#1)





 
碰巧我使用的也是react，如果vue岂不是用不了。希望您在README.md能说明一下是react代码。

**Comment by liyupi** [comment]
thanks, done
