### ISSUE TITLE
FileReader不能添加同一个图片

### ISSUE THREAD

**Issue by lanweipeng** [liyupi/yu-image-uploader#4]
当删除一个图片时，如果再次添加它，不能添加。因为FileReader不能添加同一个图片。这是个bug。

**Comment by liyupi** [comment]
可以贴出截图么，自测没出现这个问题，fileReader是局部new的

**Comment by lanweipeng** [comment]
视频我传到我服务器，你可以打开看我的录屏。（需要等待几秒）
http://121.199.39.131:8888/video.mp4
视频操作是在你READE.md的演示链接操作的。
视频一开始有一个图片，当我删掉它，再次上传这个图片（刚刚上传过的图片）时，没反应，当我上传其他图片时，可以上传。
你也可以试试连续上传同一个图片，都是2+后同一张图没有没有反应的。

**Comment by liyupi** [comment]
thanks, chrome/safari等不兼容，原因是input file输入同名文件时不会触发onChange事件。
解决方案：http://staosoft.com/articledetails.aspx?aid=107
通过给input添加onClick事件（比onChange先触发）在选择图片前清除已有value

**Comment by liyupi** [comment]
已修复
